apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuxt2-spa.fullname" . }}
  labels:
    {{- include "nuxt2-spa.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{-   toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
  selector:
    {{- include "nuxt2-spa.selectorLabels" . | nindent 4 }}

