apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nuxt3.fullname" . }}
  labels:
    {{- include "nuxt3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "nuxt3.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "nuxt3.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{  .Chart.Name  }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.servicePort}}
          resources:
            {{ toYaml .Values.resources }}

          env:
            - name: NITRO_PORT
              value: "{{ .Values.service.servicePort | default 80 }}"
          {{- range $key, $val := .Values.config.extraEnvVars }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end}}
