# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
fullnameOverride: ""
image:
  repository: repo
  tag: mytag
  pullPolicy: IfNotPresent
  resources: {}
    # requests:
  #   cpu: 200m
  #   memory: 300Mi
  #  readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 3
    periodSeconds: 5
  #  livenessProbe: {}
  #  # Example (replace livenessProbe: {} with the following)::
  livenessProbe:
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 40
    periodSeconds: 10
service:
  name: Node
  type: ClusterIP
  servicePort: 80
  targetPort: 80
  # name: Node
  # type: NodePort
  # servicePort: 3000

ingress:
  enabled: true
  annotations: {}
  # cert-manager.io/cluster-issuer: cluster-issuer
  # kubernetes.io/ingress.class: nginx
  hosts:
    - nuxt2-spa.local
  tls:
    - hosts:
        - nuxt2-spa.local
      secretName: nuxt2-spa-tls


config:
  nodeEnv: "prod"
#  port: 80
  extraEnvVars:
    #just an example
    ACCEPTED_HOSTS: "example.com"