apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oip-api.fullname" . }}
  labels:
    {{- include "oip-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "oip-api.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "oip-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{  .Chart.Name  }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.servicePort}}
          resources:
            {{ toYaml .Values.resources }}

          env:
            - name: TYPEORM_PASSWORD
              {{- if .Values.postgres.password.value }}
              value:  "{{ .Values.postgres.password.value }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  key:  {{ .Values.postgres.password.fromSecret.key }}
                  name: {{ .Values.postgres.password.fromSecret.name }}
              {{ end }}
            - name: TYPEORM_USERNAME
              {{- if .Values.postgres.user.value }}
              value: "{{ .Values.postgres.user.value }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.postgres.user.fromSecret.key }}
                  name: {{ .Values.postgres.user.fromSecret.name }}
              {{ end }}
            - name: TYPEORM_DATABASE
              value : "{{ .Values.postgres.db }}"
            - name: TYPEORM_HOST
              value : "{{ .Values.postgres.host }}"
            - name: PG_PORT
              value : "{{ .Values.postgres.port }}"
            - name: SERVER_PORT
              value : "{{ .Values.service.servicePort | default 80 }}"