image:
  repository: "eu.gcr.io/oip-cluster/realconsultingdata/apis/bitbucket_realconsultingdata_astronot-api"
  tag: "main-af1e2a4"
service:
  name: Node
  port: 80
  type: ClusterIP
  servicePort: 80
  targetPort: 80
postgres:
  db: "astronot"
  host: "10.128.16.3"
  user:
    fromSecret:
      key: "MASTER_DB_ADMIN_USERNAME"
      name: "saas-defaults"
  password:
    fromSecret:
      key: "MASTER_DB_ADMIN_PASSWORD"
      name: "saas-defaults"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
    -
      api.astronot.io
  tls:
    - hosts:
        - api.astronot.io
      secretName: astronot-api-tls